import Link from "next/link";
import type { Metadata } from "next";
import "./homepage.css";
import { HomepagePresentation } from "@/components/homepage-presentation";

export const metadata: Metadata = { title: "AURA | Du temps pour soigner. Du lien pour rassurer.", description: "AURA relie patients, proches autorisés et équipes : planning, permissions, visites et activités. Une clinique mieux coordonnée, un séjour plus serein et moins de papier." };
const demo = "mailto:contact@auradh.com?subject=Demande%20de%20d%C3%A9monstration%20AURA";
const pilot = "mailto:contact@auradh.com?subject=Lancer%20un%20pilote%20AURA";
function Icon({ name }: { name: "time" | "link" | "heart" | "leaf" | "globe" | "shield" }) {
 const paths={time:<><circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/></>,link:<><rect x="3" y="4" width="7" height="6" rx="2"/><rect x="14" y="14" width="7" height="6" rx="2"/><path d="M7 10v7h7M10 7h7v7"/></>,heart:<path d="M12 20S3 14 3 8a5 5 0 0 1 9-3 5 5 0 0 1 9 3c0 6-9 12-9 12Z"/>,leaf:<><path d="M20 3C8 2 3 8 5 15c7 3 14-2 15-12Z"/><path d="m3 21 12-12"/></>,globe:<><circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/></>,shield:<><path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/></>};
 return <svg viewBox="0 0 24 24" width="24" height="24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>;
}
const benefits=[
{icon:"time" as const,title:"Retrouver du temps",feature:"Un planning et des demandes centralisés.",benefit:"Moins de recherches, d’appels et de relances. Plus de disponibilité pour le patient."},
{icon:"link" as const,title:"Avancer ensemble",feature:"Une vue partagée selon le rôle de chacun.",benefit:"Soignants et accueil savent ce qui est prévu, décidé ou à traiter. La coordination devient plus simple."},
{icon:"heart" as const,title:"Rassurer au quotidien",feature:"Des repères pour le patient. Un portail proche sous consentement.",benefit:"Une journée plus lisible et un lien maintenu avec les proches autorisés."},
{icon:"leaf" as const,title:"Alléger l’empreinte",feature:"Des démarches numériques et des indicateurs d’impact.",benefit:"Moins d’impressions et de processus manuels. Des progrès à évaluer pendant le pilote."}];
const chapters=[
["00:00","Le séjour connecté","Planning, permissions, visites, activités et informations utiles réunis dans une plateforme."],
["00:08","Des repères pour le patient","Le patient consulte sa journée, retrouve les informations du séjour et fait ses demandes simplement."],
["00:16","Une équipe coordonnée","AURA Pulse rassemble les informations opérationnelles. Chacun voit ce qui est utile à son rôle."],
["00:24","Des permissions tracées","Demande du patient, validation du médecin et du cadre, puis enregistrement du départ et du retour par l’accueil."],
["00:32","Le lien avec les proches","Le proche autorisé consulte uniquement les informations que le patient choisit de partager. L’accès est modifiable et révocable."],
["00:40","Une expérience multilingue","Des interfaces en français, anglais, arabe, chinois et turc, sur ordinateur et mobile."],
["00:48","Un impact responsable","AURA Impact suit les usages numériques et les estimations de papier et d’impact. Les chiffres de la démo sont fictifs, non certifiés."],
["00:56","Un pilote dans votre clinique","Un périmètre ciblé pour évaluer les usages, les gains de temps, l’expérience du séjour et la réduction du papier."]];
export default function HomePage(){return <main className="aura-home ah-v2">
<a className="ah-skip" href="#presentation">Aller au contenu</a>
<header className="ah-nav"><Link href="/" className="ah-brand" aria-label="AURA — accueil"><span>A</span>AURA</Link><nav aria-label="Navigation publique"><a className="ah-nav-detail" href="#solution">La solution</a><a className="ah-nav-detail" href="#patient">Patients & proches</a><a className="ah-nav-detail" href="#impact">Impact</a><Link className="ah-btn ah-outline" href="/login">Se connecter ↗</Link></nav></header>
<section id="presentation" className="ah-hero"><div className="ah-hero-copy"><p className="ah-kicker"><span className="ah-dot"/> LE SÉJOUR PATIENT, MIEUX ORCHESTRÉ</p><h1>Du temps pour soigner.<br/><em>Du lien pour rassurer.</em></h1><p className="ah-lead">Une clinique mieux coordonnée.<br/>Des patients et des proches mieux accompagnés.</p><p className="ah-intro">AURA relie le quotidien du séjour : planning, permissions, visites, activités et informations utiles. La bonne information circule. Chacun retrouve ses repères.</p><div className="ah-actions"><a className="ah-btn ah-primary" href={demo}>Demander une démo ↗</a><a className="ah-btn ah-outline" href="#video"><span className="ah-play" aria-hidden="true">▶</span> Voir AURA en 1 minute</a></div><div className="ah-hero-proof"><span><Icon name="shield"/> Accès selon le rôle</span><span><Icon name="globe"/> 5 langues</span><span><Icon name="leaf"/> Moins de papier</span></div></div>
<div className="ah-product"><div className="ah-product-head"><span><b>AURA</b> / PULSE</span><span className="ah-live"><span className="ah-dot"/> Vue opérationnelle</span></div><div className="ah-product-title"><span className="ah-kicker">TOUT LE MONDE AVANCE DANS LE MÊME SENS</span><h2>La journée, en un regard.</h2></div><img src="/aura-pulse.jpg" alt="Écran réel AURA Pulse : patients, permissions, rendez-vous et visites, avec des données fictives" width="1200" height="675" fetchPriority="high"/><div className="ah-product-foot"><div><Icon name="link"/><span>Une information<br/><strong>partagée</strong></span></div><div><Icon name="time"/><span>Des décisions<br/><strong>tracées</strong></span></div></div><p className="ah-demo-label">Écran réel de l’application · données fictives</p></div></section>
<div className="ah-audiences"><span>UNE PLATEFORME. UN PARCOURS COMMUN.</span><div>Patient <i>↔</i> Proche autorisé <i>↔</i> Soignants <i>↔</i> Accueil <i>↔</i> Direction</div></div>
<section id="solution" className="ah-section"><div className="ah-section-heading"><div><p className="ah-kicker">DES FONCTIONS UTILES. DES BÉNÉFICES CONCRETS.</p><h2>Moins de friction dans les processus.<br/><em>Plus d’attention dans le séjour.</em></h2></div><p>AURA organise le quotidien autour du patient. Il complète le parcours de séjour, sans remplacer le dossier médical.</p></div><div className="ah-grid">{benefits.map(({icon,title,feature,benefit})=><article key={title}><span className="ah-icon"><Icon name={icon}/></span><h3>{title}</h3><p className="ah-feature">{feature}</p><p>{benefit}</p></article>)}</div>
<div className="ah-workflow"><div><p className="ah-kicker">UN EXEMPLE, TOUT SIMPLEMENT</p><h3>Une permission, de la demande au retour.</h3><p>Un circuit lisible et horodaté, pour savoir où en est chaque demande.</p></div><ol><li><span>01</span><strong>Le patient demande</strong><small>Un formulaire clair</small></li><li><span>02</span><strong>Médecin + cadre valident</strong><small>Deux décisions tracées</small></li><li><span>03</span><strong>L’accueil suit</strong><small>Départ et retour réels</small></li></ol></div></section>
<section id="video" className="ah-section ah-video-section"><div className="ah-section-heading"><div><p className="ah-kicker">COMPRENDRE AURA EN UNE MINUTE</p><h2>Une solution qui se voit.<br/><em>Une valeur qui se comprend.</em></h2></div><p>Du quotidien du patient au pilotage de la clinique : découvrez ce que fait AURA, pour qui, et ce que cela change.</p></div><div className="ah-video-frame"><div className="ah-video-top"><span>AURA / LA PRÉSENTATION</span><span>64 SECONDES · 8 CHAPITRES</span></div><HomepagePresentation /><div className="ah-video-bottom"><span>Sous-titres intégrés · sans audio</span><span>Écrans de démonstration & illustrations · données fictives</span></div></div><details className="ah-transcript"><summary>Les 8 chapitres et la version texte <span aria-hidden="true">＋</span></summary><div>{chapters.map(([time,title,text])=><article key={time}><span>{time}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></details><div className="ah-video-links"><Link href="/demo">Explorer la démonstration détaillée ↗</Link><a href="/aura-explainer-v2.mp4" download>Télécharger la vidéo ↗</a></div></section>
<section id="patient" className="ah-section ah-human"><div className="ah-human-intro"><p className="ah-kicker">LE SÉJOUR EST AUSSI UNE EXPÉRIENCE HUMAINE</p><h2>Être informé.<br/>Se sentir accompagné.<br/><em>Garder le lien.</em></h2><p>Le bien-être passe aussi par des repères : comprendre sa journée, accéder aux informations et rester en lien avec ceux qui comptent.</p><div className="ah-human-chips"><span>Clarté</span><span>Autonomie</span><span>Lien</span></div></div><div className="ah-human-cards"><article><span className="ah-role">POUR LE PATIENT</span><h3>Une journée plus lisible.</h3><p>Rendez-vous, activités, visites et informations pratiques dans un même espace. Des demandes simples à suivre, pour mieux comprendre le séjour et y participer.</p><ul><li>Retrouver le programme de sa journée</li><li>Consulter les activités et organiser les visites</li><li>Suivre ses demandes de permission</li></ul></article><article><span className="ah-role">POUR LES PROCHES AUTORISÉS</span><h3>Rester présent, même à distance.</h3><p>Un portail proche pour consulter les informations que le patient a choisi de partager : planning, visites, présence ou vie du séjour, selon les autorisations accordées.</p><div className="ah-consent"><Icon name="shield"/><span>Le patient garde la main.<br/><strong>Accès modifiable et révocable. Dossier médical privé.</strong></span></div></article></div></section>
<section className="ah-section ah-language"><div className="ah-language-copy"><span className="ah-icon"><Icon name="globe"/></span><div><p className="ah-kicker">COMPRENDRE, QUELLE QUE SOIT SA LANGUE</p><h2>Un séjour plus accessible.</h2><p>Des interfaces multilingues sur ordinateur et mobile, pour faciliter la compréhension et accompagner des publics différents.</p></div></div><div className="ah-language-list"><span>Français</span><span>English</span><span lang="ar" dir="rtl">العربية</span><span lang="zh">中文</span><span lang="tr">Türkçe</span></div></section>
<section id="impact" className="ah-impact"><div className="ah-section ah-impact-inner"><div><p className="ah-kicker">UN QUOTIDIEN PLUS SOBRE</p><h2>Moins de papier.<br/>Moins de démarches.<br/><em>Plus de sens.</em></h2><p>Une demande sans formulaire imprimé. Une validation sans feuille à faire circuler. Une information retrouvée sans relance : l’impact commence dans les gestes du quotidien.</p><Link className="ah-btn ah-impact-link" href="/performance-impact">Découvrir Performance & Impact ↗</Link></div><div className="ah-impact-cards"><article><Icon name="leaf"/><div><h3>Dématérialiser</h3><p>Réduire les impressions grâce aux demandes et validations numériques.</p></div></article><article><Icon name="link"/><div><h3>Simplifier</h3><p>Limiter les recherches et démarches administratives répétées.</p></div></article><article><Icon name="time"/><div><h3>Mesurer les progrès</h3><p>Suivre les usages et calibrer les estimations de papier et d’impact pendant le pilote.</p></div></article><p className="ah-impact-note">Les indicateurs environnementaux sont des estimations à adapter au contexte de l’établissement. Les chiffres de démonstration sont fictifs, non certifiés.</p></div></div></section>
<section id="pilote" className="ah-section ah-pilot"><p className="ah-kicker">LE PROCHAIN PARCOURS, C’EST LE VÔTRE</p><h2>Voyez la différence.<br/><em>Mesurez-la dans votre clinique.</em></h2><p>Commençons par une démo, puis un pilote ciblé. Ensemble, définissons les équipes, les usages et les indicateurs : temps, coordination, expérience du séjour et réduction du papier.</p><div className="ah-pilot-steps"><span><b>01</b> Découvrir</span><span><b>02</b> Tester</span><span><b>03</b> Évaluer</span></div><div className="ah-actions"><a className="ah-btn ah-primary" href={demo}>Demander une démo ↗</a><a className="ah-btn ah-outline" href={pilot}>Lancer un pilote ↗</a></div></section>
<footer className="ah-footer"><Link className="ah-brand" href="/"><span>A</span>AURA</Link><p>Du temps pour soigner. Du lien pour rassurer.</p><a href="mailto:contact@auradh.com">contact@auradh.com</a><Link href="/login">Se connecter ↗</Link></footer>
</main>;}
