"use client";
import { useEffect, useState } from "react";

const scenes = [
{tag:"LA SOLUTION",title:"Le séjour, enfin connecté.",points:["Un parcours quotidien centralisé","Une interface pour chaque rôle","Des informations faciles à retrouver"],image:"/aura-pulse.jpg",caption:"AURA réunit planning, permissions, visites, activités et informations de séjour dans une seule plateforme."},
{tag:"EXPÉRIENCE PATIENT",title:"Des repères. Plus de sérénité.",points:["Savoir ce qui est prévu","Retrouver les informations utiles","Faire ses demandes simplement"],image:"/aura-pulse.jpg",caption:"Le patient retrouve ses rendez-vous et ses activités. Il comprend sa journée et sait où trouver les informations utiles."},
{tag:"COORDINATION",title:"La bonne information. Au bon moment.",points:["Patients, soignants et accueil reliés","Visibilité selon le rôle de chacun","Moins de recherches et de relances"],image:"/aura-pulse.jpg",caption:"AURA Pulse rassemble les informations opérationnelles pour aider les équipes à coordonner la journée sans multiplier les appels."},
{tag:"PERMISSIONS",title:"Une demande. Un parcours tracé.",points:["Le patient fait sa demande","Médecin et cadre valident","L’accueil trace départ et retour"],image:"/aura-pulse.jpg",caption:"La permission suit un circuit clair : demande du patient, double validation, puis enregistrement du départ et du retour."},
{tag:"PATIENT & PROCHES",title:"Garder le lien. Respecter les choix.",points:["Un portail pour le proche autorisé","Les informations choisies par le patient","Un accès modifiable et révocable"],image:null,caption:"Le proche autorisé consulte les informations que le patient choisit de partager. Le dossier médical et les échanges internes restent privés."},
{tag:"MULTILINGUE",title:"Mieux comprendre. Mieux accompagner.",points:["Français, anglais, arabe, chinois et turc","Une expérience sur ordinateur et mobile","Des repères compris par davantage de patients"],image:null,caption:"Des interfaces en cinq langues facilitent la compréhension du séjour et accompagnent des patients aux besoins différents."},
{tag:"IMPACT RESPONSABLE",title:"Moins de papier. Des progrès à suivre.",points:["Demandes et validations numériques","Indicateurs d’usage et de dématérialisation","Estimations à calibrer lors du pilote"],image:"/aura-impact-v2.jpg",caption:"AURA Impact suit les usages numériques et les estimations de papier et d’impact environnemental. Les chiffres de la démo sont fictifs, non certifiés."},
{tag:"VOTRE ÉTABLISSEMENT",title:"Du temps pour soigner. Du lien pour rassurer.",points:["Des repères pour le patient et ses proches","Une équipe mieux coordonnée","Un impact à évaluer sur le terrain"],image:"/aura-pulse.jpg",caption:"Découvrez AURA, puis lancez un pilote pour mesurer les gains dans votre clinique. Contact : contact@auradh.com."}
];
const formatTime=(value:number)=>Math.floor(value/60)+":"+String(Math.floor(value%60)).padStart(2,"0");
export function HomepagePresentation(){
const [elapsed,setElapsed]=useState(0),[playing,setPlaying]=useState(false);
useEffect(()=>{if(!playing)return;let previous=performance.now();const timer=setInterval(()=>{const now=performance.now(),delta=(now-previous)/1000;previous=now;setElapsed(current=>Math.min(64,current+delta))},100);return()=>clearInterval(timer)},[playing]);
useEffect(()=>{if(elapsed>=64&&playing)setPlaying(false)},[elapsed,playing]);
const index=Math.min(7,Math.floor(elapsed/8)),scene=scenes[index];
const toggle=()=>{if(elapsed>=64)setElapsed(0);setPlaying(value=>!value)};
return <div className="ah-film" data-no-i18n aria-label="Présentation animée AURA en huit chapitres">
<div className="ah-film-scene" key={index}><div className="ah-film-copy"><p className="ah-film-tag">{String(index+1).padStart(2,"0")} / {scene.tag}</p><h3 aria-live="polite">{scene.title}</h3><ul>{scene.points.map(point=><li key={point}>{point}</li>)}</ul></div><div className="ah-film-screen">{scene.image?<><span>ÉCRAN RÉEL · DONNÉES FICTIVES</span><img src={scene.image} alt={index===6?"Écran AURA Impact avec des indicateurs fictifs de démonstration":"Écran AURA Pulse de démonstration : patients, permissions et rendez-vous"} width="1200" height="675"/></>:index===4?<><span>ILLUSTRATION DU PARCOURS</span><h4>Mon proche</h4><p>Les informations choisies par le patient</p><div className="ah-film-family">{[["Planning partagé","Rendez-vous et activités"],["Visites organisées","Un lien avec la vie du séjour"],["Consentement","Accès modifiable et révocable"]].map(([title,text])=><div key={title}><strong>{title}</strong><small>{text}</small></div>)}</div></>:<><span>UNE INTERFACE MULTILINGUE</span><div className="ah-film-languages"><span>Français</span><span>English</span><span lang="ar" dir="rtl">العربية</span><span lang="zh">中文</span><span lang="tr">Türkçe</span></div><p>Sur ordinateur et mobile</p></>}</div></div>
<p className="ah-film-caption">{scene.caption}</p>
<div className="ah-film-chapters" role="group" aria-label="Choisir un chapitre">{scenes.map((item,i)=><button type="button" key={item.tag} aria-label={"Chapitre "+(i+1)+" : "+item.tag} aria-pressed={index===i} onClick={()=>setElapsed(i*8)}><span style={{width:i<index?"100%":i===index?Math.min(100,(elapsed-i*8)/8*100)+"%":"0%"}}/></button>)}</div>
<div className="ah-film-controls"><button type="button" className="ah-film-play" onClick={toggle}>{playing?"Ⅱ Mettre en pause":elapsed>=64?"↻ Revoir la présentation":"▶ Lancer la présentation"}</button><span>{formatTime(elapsed)} / 1:04</span><div><button type="button" aria-label="Chapitre précédent" disabled={index===0} onClick={()=>setElapsed(Math.max(0,index-1)*8)}>←</button><button type="button" aria-label="Chapitre suivant" disabled={index===7} onClick={()=>setElapsed(Math.min(7,index+1)*8)}>→</button></div></div>
</div>;
}
