import Link from "next/link";

const impactMetrics = [
  ["Pages potentiellement évitées", "3 852", "Hypothèse démo : 3 pages par document dématérialisé"],
  ["Échanges numériques", "2 460", "Notifications et interactions réalisées dans AURA"],
  ["Déplacements administratifs évités", "74", "Quand un échange numérique remplace une démarche sur site"],
  ["CO₂e évité · estimation", "186 kg", "Simulation non certifiée, facteur paramétrable"],
];

export default function PerformanceImpactPage() {
  return <main className="landing landing-v2 landing-simplified">
    <header className="topbar topbar-v2"><Link href="/" className="brand"><span className="brand-mark">A</span><span>AURA</span></Link><nav className="public-nav" aria-label="Navigation Performance et Impact"><Link href="/">Accueil</Link><Link href="/demo">Démo</Link><a href="#methodologie">Méthodologie</a><Link className="button button-secondary" href="/login">Se connecter</Link></nav></header>

    <section className="hero hero-v2 hero-simplified"><div className="hero-copy"><div className="eyebrow">Performance & Impact</div><h1>Mesurer ce qu’AURA simplifie réellement.</h1><p className="hero-lead">AURA rapproche performance opérationnelle et numérique responsable : moins de démarches manuelles, davantage de traçabilité, moins de papier et des indicateurs compréhensibles par la direction.</p><div className="hero-actions"><a className="button button-primary button-large" href="mailto:contact@auradh.com?subject=Performance%20et%20Impact%20AURA">Demander une démonstration</a><Link className="button button-secondary button-large" href="/demo">Voir AURA en 2 minutes</Link></div></div><div className="product-preview product-preview-simplified"><div className="preview-top"><div><span className="preview-kicker">Pilotage établissement</span><strong>Performance & Impact</strong></div><span className="badge badge-success"><span className="status-dot"/>Mesurable</span></div><div className="preview-grid"><article className="preview-card preview-card-main"><span>Démarches digitales</span><strong>1 284</strong><small>documents et processus numérisés</small></article><article className="preview-card"><span>Coordination</span><strong>2 460</strong><small>échanges numériques</small></article><article className="preview-card"><span>Papier</span><strong>3 852 pages</strong><small>estimation démo</small></article><article className="preview-card preview-card-impact"><span>CO₂e</span><strong>186 kg</strong><small>estimation démo non certifiée</small></article></div></div></section>

    <section className="public-section public-section-simplified"><div className="section-heading"><span className="eyebrow">Performance opérationnelle</span><h2>Des gains visibles avant même de parler de carbone.</h2><p>AURA suit les flux qui structurent le séjour : permissions, mouvements, visites, demandes administratives, tâches de sortie et usages numériques.</p></div><div className="public-pillars"><article><span>01</span><h3>Réduire les relances</h3><p>Une information partagée par rôle limite les appels et les recherches d’information.</p></article><article><span>02</span><h3>Tracer les décisions</h3><p>Validations, départs, retours et actions importantes sont horodatés.</p></article><article><span>03</span><h3>Mesurer l’adoption</h3><p>Les usages numériques deviennent des indicateurs de pilotage lisibles.</p></article><article><span>04</span><h3>Identifier les frictions</h3><p>Les processus encore trop manuels deviennent visibles et priorisables.</p></article></div></section>

    <section className="public-section public-impact-section"><div className="public-impact-copy"><span className="eyebrow">AURA Impact</span><h2>Une démarche environnementale crédible parce qu’elle reste transparente.</h2><p>Les indicateurs ci-dessous illustrent le module avec des données fictives. AURA distingue les usages réellement observés des estimations calculées à partir de facteurs paramétrables.</p><div className="impact-demo-note"><strong>Données de démonstration</strong><span>Ces valeurs ne constituent ni un bilan carbone réglementaire ni une certification environnementale.</span></div></div><div className="public-impact-metrics">{impactMetrics.map(([label,value,detail])=><article key={label}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>)}</div></section>

    <section id="methodologie" className="public-section public-section-soft public-section-simplified"><div className="section-heading"><span className="eyebrow">Méthodologie</span><h2>Une méthode paramétrable établissement par établissement.</h2><p>Les facteurs peuvent être adaptés au contexte réel du pilote avant toute communication externe.</p></div><div className="journey-grid journey-grid-simplified"><article><span>1</span><div><h3>Mesurer les usages</h3><p>Documents, interactions et événements réellement réalisés dans AURA.</p></div></article><article><span>2</span><div><h3>Appliquer les hypothèses</h3><p>Pages par document, facteurs CO₂e et critères de déplacement évité sont paramétrables.</p></div></article><article><span>3</span><div><h3>Séparer mesure et estimation</h3><p>Les indicateurs calculés restent explicitement identifiés comme estimations.</p></div></article><article><span>4</span><div><h3>Calibrer avec le pilote</h3><p>Les hypothèses sont ajustées avec les données et pratiques de l’établissement.</p></div></article></div></section>

    <section className="sales-cta sales-cta-simplified"><div><span className="eyebrow">AURA FR · AURA DZ</span><h2>Performance opérationnelle et impact responsable dans la même plateforme.</h2><p>Le prochain objectif est de confronter ces indicateurs aux données d’un pilote réel afin de produire des preuves commercialement robustes.</p></div><a className="button button-primary button-large" href="mailto:contact@auradh.com?subject=Pilote%20Performance%20Impact%20AURA">Lancer un pilote</a></section>
    <footer className="public-footer public-footer-simplified"><Link className="brand" href="/"><span className="brand-mark">A</span>AURA</Link><p>Performance & Impact · contact@auradh.com</p></footer>
  </main>;
}
