import Link from "next/link";

const audiences = [
  ["Direction", "Pilotage, ROI, AURA Impact et vision multi-établissements."],
  ["Soignants", "Décisions prioritaires, planning et coordination sans multiplier les écrans."],
  ["Accueil", "Mouvements, visites et retours visibles en temps réel."],
  ["Patient", "Une journée claire, des demandes simples et les informations utiles au même endroit."],
];

export default function CommercialPage() {
  return <main className="landing landing-v2 landing-simplified">
    <header className="topbar topbar-v2"><Link href="/" className="brand"><span className="brand-mark">A</span><span>AURA</span></Link><nav className="public-nav" aria-label="Présentation commerciale"><Link href="/performance-impact">Performance & Impact</Link><Link href="/demo">Démo</Link><a className="button button-primary" href="mailto:contact@auradh.com?subject=Rendez-vous%20AURA">Prendre rendez-vous</a></nav></header>

    <section className="hero hero-v2 hero-simplified"><div className="hero-copy"><div className="eyebrow">Présentation commerciale AURA</div><h1>Une clinique plus fluide, du patient à la direction.</h1><p className="hero-lead">AURA orchestre le séjour quotidien autour du système d’information existant : patient, équipes, planning, permissions, mouvements, communication, performance et impact responsable.</p><div className="hero-actions"><a className="button button-primary button-large" href="mailto:contact@auradh.com?subject=Pilote%20AURA">Demander un pilote</a><Link className="button button-secondary button-large" href="/demo">Ouvrir la démo</Link></div><div className="market-chips"><span>AURA FR</span><span>AURA DZ</span><span>Multi-établissements</span><span>5 langues</span></div></div><div className="product-preview product-preview-simplified"><div className="preview-top"><div><span className="preview-kicker">Extrait réel de l’interface démo</span><strong>Cockpit séjour</strong></div><span className="badge badge-success"><span className="status-dot"/>Temps réel</span></div><div className="preview-grid"><article className="preview-card preview-card-main"><span>08:45</span><strong>Patient présent</strong><small>Chambre 214 · planning à jour</small></article><article className="preview-card"><span>À traiter</span><strong>2 validations</strong><small>priorisées pour l’équipe</small></article><article className="preview-card"><span>Sortie</span><strong>Retour 18:00</strong><small>mouvement horodaté</small></article><article className="preview-card preview-card-impact"><span>Impact</span><strong>3 852 pages</strong><small>potentiellement évitées · démo</small></article></div></div></section>

    <section className="public-section public-section-simplified"><div className="section-heading"><span className="eyebrow">Une interface par besoin</span><h2>La complexité reste dans le produit, pas devant l’utilisateur.</h2><p>Chaque rôle voit d’abord ses priorités. Les fonctions secondaires restent accessibles dans « Plus ».</p></div><div className="public-pillars">{audiences.map(([title,text],index)=><article key={title}><span>0{index+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>

    <section className="public-section public-section-soft public-section-simplified"><div className="section-heading"><span className="eyebrow">Ce qu’un prospect doit retenir</span><h2>AURA ne remplace pas le dossier médical. Il fluidifie tout ce qui l’entoure.</h2></div><div className="journey-grid journey-grid-simplified"><article><span>1</span><div><h3>Expérience patient</h3><p>Planning, visites, activités, demandes et informations de séjour dans un espace lisible.</p></div></article><article><span>2</span><div><h3>Coordination</h3><p>Moins d’appels, de doubles saisies et de zones grises entre équipes.</p></div></article><article><span>3</span><div><h3>Pilotage</h3><p>Pulse, ROI et tableaux de bord donnent à la direction une lecture commune.</p></div></article><article><span>4</span><div><h3>Impact</h3><p>Dématérialisation et indicateurs responsables intégrés à la proposition de valeur.</p></div></article></div></section>

    <section className="public-section public-impact-section"><div className="public-impact-copy"><span className="eyebrow">AURA Impact</span><h2>Un argument différenciant sans greenwashing.</h2><p>Les chiffres de la démo sont présentés comme des simulations. La méthodologie devient paramétrable afin d’être recalibrée sur un pilote réel avant toute revendication externe.</p><Link className="button button-secondary" href="/performance-impact">Voir Performance & Impact</Link></div><div className="public-impact-metrics"><article><span>Documents numériques</span><strong>1 284</strong><small>données démo</small></article><article><span>Pages évitées · est.</span><strong>3 852</strong><small>hypothèse paramétrable</small></article><article><span>Déplacements évités · est.</span><strong>74</strong><small>administratif</small></article><article><span>CO₂e · est.</span><strong>186 kg</strong><small>non certifié</small></article></div></section>

    <section className="sales-cta sales-cta-simplified"><div><span className="eyebrow">Prochaine étape</span><h2>Passer de la démo au pilote.</h2><p>Configuration par établissement, rôles, modules, pays, langues et priorités opérationnelles. Le pilote permettra de transformer les hypothèses en preuves mesurées.</p></div><a className="button button-primary button-large" href="mailto:contact@auradh.com?subject=Pilote%20AURA">Parler du pilote</a></section>
    <footer className="public-footer public-footer-simplified"><Link className="brand" href="/"><span className="brand-mark">A</span>AURA</Link><p>Présentation commerciale · données de démonstration · contact@auradh.com</p></footer>
  </main>;
}
