import Link from "next/link";
import { AuraCopy } from "@/components/aura-copy";

const audiences = [
  ["Direction", "Pilotage, ROI, AURA Impact et vision multi-établissements."],
  ["Soignants", "Décisions prioritaires, planning et coordination sans multiplier les écrans."],
  ["Accueil", "Mouvements, visites et retours visibles en temps réel."],
  ["Patient", "Une journée claire, des demandes simples et les informations utiles au même endroit."],
];

export default function CommercialPage() {
  return <main className="landing landing-v2 landing-simplified">
    <header className="topbar topbar-v2"><Link href="/" className="brand"><span className="brand-mark">A</span><span>AURA</span></Link><nav className="public-nav" aria-label="Présentation commerciale"><Link href="/performance-impact">Performance & Impact</Link><Link href="/demo">Démo</Link><a className="button button-primary" href="mailto:contact@auradh.com?subject=Rendez-vous%20AURA"><AuraCopy id="requestDemo" /></a></nav></header>

    <section className="hero hero-v2 hero-simplified"><div className="hero-copy"><div className="eyebrow">AURA · orchestration du séjour patient</div><h1><AuraCopy id="heroTitle" /></h1><p className="hero-lead"><AuraCopy id="heroLead" /></p><div className="hero-actions"><a className="button button-primary button-large" href="mailto:contact@auradh.com?subject=Pilote%20AURA"><AuraCopy id="requestDemo" /></a><Link className="button button-secondary button-large" href="/demo"><AuraCopy id="discoverTwoMinutes" /></Link></div><div className="market-chips"><span>AURA FR</span><span>AURA DZ</span><span>Multi-établissements</span><span>5 langues</span></div></div><div className="product-preview product-preview-simplified"><div className="preview-top"><div><span className="preview-kicker">AURA Demo</span><strong>Cockpit séjour</strong></div><span className="badge badge-success"><span className="status-dot"/>Temps réel</span></div><div className="preview-grid"><article className="preview-card preview-card-main"><span>08:45</span><strong>Patient présent</strong><small>Chambre 214 · planning à jour</small></article><article className="preview-card"><span>À traiter</span><strong>2 validations</strong><small>priorisées pour l’équipe</small></article><article className="preview-card"><span>Sortie</span><strong>Retour 18:00</strong><small>mouvement horodaté</small></article><article className="preview-card preview-card-impact"><span>Impact</span><strong>3 852 pages</strong><small>potentiellement évitées · démo</small></article></div></div></section>

    <section className="public-section public-section-simplified"><div className="section-heading"><span className="eyebrow">Valeur établissement</span><h2><AuraCopy id="valueTitle" /></h2><p><AuraCopy id="valueLead" /></p></div><div className="public-pillars"><article><span>01</span><h3><AuraCopy id="pillarPatientTitle" /></h3><p><AuraCopy id="pillarPatientText" /></p></article><article><span>02</span><h3><AuraCopy id="pillarTeamTitle" /></h3><p><AuraCopy id="pillarTeamText" /></p></article><article><span>03</span><h3><AuraCopy id="pillarPerformanceTitle" /></h3><p><AuraCopy id="pillarPerformanceText" /></p></article><article><span>04</span><h3><AuraCopy id="pillarImpactTitle" /></h3><p><AuraCopy id="pillarImpactText" /></p></article></div></section>

    <section className="public-section public-section-soft public-section-simplified"><div className="section-heading"><span className="eyebrow">Une interface par métier</span><h2>Chacun voit uniquement ce dont il a besoin.</h2><p>Les services secondaires restent disponibles sans encombrer la navigation principale.</p></div><div className="journey-grid journey-grid-simplified">{audiences.map(([title,text],index)=><article key={title}><span>{index+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>

    <section className="public-section public-impact-section"><div className="public-impact-copy"><span className="eyebrow">AURA Impact</span><h2><AuraCopy id="performanceImpactTitle" /></h2><p><AuraCopy id="impactLead" /></p><div className="impact-demo-note"><strong>Données de démonstration</strong><span><AuraCopy id="demoDataNote" /></span></div><div style={{ marginTop: 18 }}><Link className="button button-secondary" href="/performance-impact">Performance & Impact</Link></div></div><div className="public-impact-metrics"><article><span>DOCUMENTS NUMÉRIQUES</span><strong>1 284</strong><small>données démo</small></article><article><span>PAGES ÉVITÉES · EST.</span><strong>3 852</strong><small>hypothèse paramétrable</small></article><article><span>DÉPLACEMENTS ÉVITÉS · EST.</span><strong>74</strong><small>administratif</small></article><article><span>CO₂e ÉVITÉ · EST.</span><strong>186 kg</strong><small>non certifié</small></article></div></section>

    <section className="sales-cta sales-cta-simplified"><div><span className="eyebrow">AURA FR · AURA DZ</span><h2><AuraCopy id="pilotTitle" /></h2><p><AuraCopy id="pilotLead" /></p></div><a className="button button-primary button-large" href="mailto:contact@auradh.com?subject=Pilote%20AURA"><AuraCopy id="requestDemo" /></a></section>
    <footer className="public-footer public-footer-simplified"><Link className="brand" href="/"><span className="brand-mark">A</span>AURA</Link><p>Présentation commerciale · données de démonstration · contact@auradh.com</p></footer>
  </main>;
}
