create table if not exists public.ux_events (
  id bigint generated by default as identity primary key,
  facility_id uuid not null references public.facilities(id) on delete cascade,
  role text not null,
  event_type text not null check (event_type in ('page_view','nav_click','action_click','menu_open')),
  path text not null,
  target text,
  session_id uuid not null,
  created_at timestamptz not null default now()
);

alter table public.ux_events enable row level security;

grant select, insert on table public.ux_events to authenticated;
grant usage, select on sequence public.ux_events_id_seq to authenticated;

create policy "ux_events_insert_test_session"
on public.ux_events
for insert
to authenticated
with check (public.has_facility_access(facility_id));

create policy "ux_events_leadership_read"
on public.ux_events
for select
to authenticated
using (
  exists (
    select 1
    from public.facility_memberships fm
    where fm.user_id = (select auth.uid())
      and fm.facility_id = ux_events.facility_id
      and fm.active = true
      and fm.role::text in ('admin','governance','manager')
  )
);

create index if not exists ux_events_facility_created_idx on public.ux_events (facility_id, created_at desc);
create index if not exists ux_events_session_idx on public.ux_events (session_id, created_at);
create index if not exists ux_events_role_idx on public.ux_events (role, created_at desc);
